M48
; DRILL file {KiCad 7.0.6} date Tue Jul 11 08:11:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-11T08:11:05-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X0.0984Y2.6575
X0.0984Y0.0984
X4.4291Y2.6575
X4.4291Y0.0984
T2
X0.3317Y0.4831
X0.7817Y0.4831
T0
M30
